### PR TITLE
Stability update

### PR DESCRIPTION
**Pull request by snopachinda-gpi**
This update adds additional safeguards and pool releases to several routes. 

The goal is to make the API more stable and increase uptime based on the notion that pools were not being closed properly - thus causing the database to become unresponsive. 

Additional logging handlers were added and new logging tables for modules were added.

The following modules were tested to ensure no pools in the database were straggling and all opened clients were closed properly:

- Weather 
- Trends 
- Legacy EA 
- EA Explorer 
- Sun glare 
- Crash Map 
- Jurisdiction 
- Report 
- Maintenance 
- Report 
- Admin 
- Signals

### CODE REVIEW

**Comment by mcollins-GPI** [comment]
Thank you for going through all the modules and improving the routes. The closer we get to launching this thing (and the more it improves), the more excited I get :) Nice job!

**Comment by mcollins-GPI** [comment]
Should we delete, or do you need to check anything?

**Comment by snopachinda-gpi** [comment]
No problem! One thing I noticed between 'stability-update' and 'stability-update-upgrade' is that I could not access the documentation page for the latter. I think it may have to do with the package updates. I use the documentation page to run custom export packages, and I couldn't do it with 'stability-update-upgrade'.

**Comment by mcollins-GPI** [comment]
Has the documentation package changed format or something? I probably borked something in my haste.

***@***.***
Michael Collins
d 646.791.8814  | c 651.323.8431
Greenman-Pedersen, Inc. An Equal Opportunity Employer

**Pull request merged**
